### ISSUE TITLE
Data fetching

### ISSUE THREAD

**Issue by imadatyatalah** [MarySed/chakra-bookshelf#3]
I think [useSwr](https://swr.vercel.app/) (you can use it with [axios](https://swr.vercel.app/docs/data-fetching#axios) if you wish) or [react-query](https://react-query.tanstack.com/) will be a better choice for fetching data.

**Comment by MarySed** [comment]
@imadatyatalah Yeah, SWR is what I'm planning on implementing later 
How do you feel about react-query? I've never used it before but I've heard good things

**Comment by imadatyatalah** [comment]
@MarySed I prefer react-query even it's kinda harder to learn than useSwr but I think it's better.
Take a look at [comparison between useSwr ana react-query](https://react-query.tanstack.com/comparison)

**Comment by MarySed** [comment]
@imadatyatalah Thanks for the input and link! I'll definitely be taking a look at react-query too then 😄 
Just a heads up that I won't be able to work much on the repo until the weekend so things might go a bit quiet around here (work is busy 😱 )

**Comment by imadatyatalah** [comment]
@MarySed not a problem, if you decided which tool you'll choose for data fetching just tell me I can implement it
